"""add resume fields to jobs

Revision ID: 4ebd432e4e3d
Revises: c1a7e8161ede
Create Date: 2026-05-13 18:01:26.292251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ebd432e4e3d'
down_revision: Union[str, Sequence[str], None] = 'c1a7e8161ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=False),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_status_history_id'), 'job_status_history', ['id'], unique=False)
    op.drop_index(op.f('ix_job status history_id'), table_name='job status history')
    op.drop_table('job status history')
    op.add_column('jobs', sa.Column('resume_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'resume_filename')
    op.create_table('job status history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('old_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('new_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('job status history_job_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('job status history_pkey'))
    )
    op.create_index(op.f('ix_job status history_id'), 'job status history', ['id'], unique=False)
    op.drop_index(op.f('ix_job_status_history_id'), table_name='job_status_history')
    op.drop_table('job_status_history')
    # ### end Alembic commands ###
