"""add google token column to users

Revision ID: 4ebe8e27e109
Revises: 5ba7c2e7b909
Create Date: 2026-06-25 10:06:25.946459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ebe8e27e109'
down_revision: Union[str, Sequence[str], None] = '5ba7c2e7b909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_token')
    # ### end Alembic commands ###
