"""add resume file path to jobs

Revision ID: 5d8bd6296e68
Revises: 3cb0e8949524
Create Date: 2026-05-20 18:40:17.865277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8bd6296e68'
down_revision: Union[str, Sequence[str], None] = '3cb0e8949524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('resume_file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'resume_file_path')
    # ### end Alembic commands ###
